### ISSUE TITLE
Входящие не работают

### ISSUE THREAD

**Issue by jaloveast1k** [konaire/SipCaller#1]
Собрал Ваш проект, исходящие ок, а вот входящие - в ресивер ничего не попадает.
Не знаете почему?
Android 9, OnePlus 3

**Comment by Daracul** [comment]
> Собрал Ваш проект, исходящие ок, а вот входящие - в ресивер ничего не попадает.
> Не знаете почему?
> Android 9, OnePlus 3

Привет. 
Скорее всего из-за ограничений новых версий Android, ресиверы созданные в манифесте не работают ... Попробуй создавать их динамически в коде, например в CallService.
Но тем не менее, у меня получилось ловить входящий звонок на телефоне, но при этом не воспроизводится никаких звуков (пробовал звонить с телефона на телефон).

**Comment by konaire** [comment]
Все верно проблема в "Background Execution Limits" для новых версий андроида:
> apps cannot use their manifest to register for implicit broadcasts

Как правильно сказал @Daracul нужно байндить `CallReceiver` динамически. Я запушил изменения с тем как это должно работать сейчас, данный код работает на моих устройствах, проверьте на ваших.

> Но тем не менее, у меня получилось ловить входящий звонок на телефоне, но при этом не воспроизводится никаких звуков (пробовал звонить с телефона на телефон).

Скорее всего проблема в драйверах на сервере, попробуйте создать аккаунты на [Linphone](https://www.linphone.org/freesip/myaccount) и позвонить от туда.
